SCRUM-81-DETALLE-EVENTO
ArielDRighi/Eventop-Frontend pull request #16
Opened 2024-11-23 15:37 UTC by LeoGittt

se modifico el placeholder del evento y el detalle de la card

2024-11-23 15:37 UTC, FedericoLGaitan approved these changes

2024-11-23 15:38 UTC, FedericoLGaitan approved these changes

2024-11-25 02:41 UTC, federicovanni approved these changes

2024-11-25 21:29 UTC, ArielDRighi requested changes
Esta repetido el formulario de compra

2024-11-25 22:14 UTC, ArielDRighi approved these changes

2024-11-25 23:34 UTC, merged